"""Generates the C# message types and registries of UnityLudometry.Protocol from the JSON Schemas.

Usage:  python protocol/codegen/csharp.py           (writes csharp/UnityLudometry.Protocol/Generated/)
        python protocol/codegen/csharp.py --check   (exit 1 if the committed output is stale)

Python 3.10+ standard library only. The schemas are read by schema_ir.py (shared with the Python generator).
C# specifics: common types with hand-written counterparts map to AgentMode, ProtocolError and JsonValue; raw JSON
objects map to JsonObject; unknown properties are kept in ProtocolMessage.Extra.
"""
from __future__ import annotations

import json
import re
import sys

from schema_ir import PROTOCOL, ClassDef, IrType, Model, Prop, SchemaError, build, pascal

OUT_DIR = PROTOCOL / "csharp" / "UnityLudometry.Protocol" / "Generated"
NAMESPACE = "UnityLudometry.Protocol.Messages"
HEADER = "// <auto-generated>\n// Generated by protocol/codegen/csharp.py from protocol/schema. Do not edit.\n// </auto-generated>\n#nullable enable\n"


def cs(t: IrType, optional: bool) -> str:
    base = {"string": "string", "long": "long", "double": "double", "bool": "bool", "mode": "AgentMode",
            "json": "JsonValue", "object": "JsonObject", "error": "ProtocolError"}.get(t.kind)
    if t.kind == "class":
        base = t.name
    if t.kind == "list":
        base = f"List<{cs(t.item, False)}>"
    return base + ("?" if optional or t.nullable else "")


def cs_name(cls: ClassDef, p: Prop) -> str:
    name = pascal(p.json_name)
    if name == cls.name or name == "Extra":
        name += "Value"
    return name


def xml(text: str) -> str:
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = re.sub(r"`([^`]+)`", r"<c>\1</c>", text)
    return " ".join(text.split())


def reader(t: IrType) -> str:
    """A Func<JsonValue, string, T> expression for list items / nested messages."""
    return {
        "string": "ObjectReader.ReadString", "long": "ObjectReader.ReadInt64", "double": "ObjectReader.ReadDouble",
        "bool": "ObjectReader.ReadBoolean", "mode": "ObjectReader.ReadMode", "json": "ObjectReader.ReadValue",
        "object": "ObjectReader.ReadObject", "error": "global::UnityLudometry.Protocol.Envelopes.ProtocolError.Read",
        "class": f"global::{NAMESPACE}.{t.name}.Read",
    }.get(t.kind) or f"(v, p) => ObjectReader.ReadList(v, p, {reader(t.item)})"


def read_expr(p: Prop) -> str:
    t, n = p.type, json.dumps(p.json_name)
    nullable_required = p.required and t.nullable
    k = t.kind
    if k in ("string", "long", "double", "bool"):
        method = {"string": "String", "long": "Int64", "double": "Double", "bool": "Boolean"}[k]
        if nullable_required:
            return f"r.RequiredNullable{method}({n})"
        return f"r.Required{method}({n})" if p.required else f"r.Optional{method}({n})"
    if k == "mode":
        return f"r.RequiredMode({n})" if p.required else f"r.OptionalMode({n})"
    if k == "json":
        return f"r.RequiredValue({n})" if p.required else f"r.OptionalValue({n})"
    if k == "object":
        return f"r.RequiredObject({n})" if p.required else f"r.OptionalObject({n})"
    if k in ("class", "error"):
        fn = reader(t)
        if nullable_required:
            return f"r.RequiredNullable({n}, {fn})"
        return f"r.Required({n}, {fn})" if p.required else f"r.Optional({n}, {fn})"
    if k == "list":
        return f"r.RequiredArray({n}, {reader(t.item)})" if p.required else f"r.OptionalArray({n}, {reader(t.item)})"
    raise SchemaError(k)


def write_value(t: IrType, expr: str, depth: int) -> list[str]:
    """Statements writing a non-null value (no property name)."""
    k = t.kind
    if k == "string":
        return [f"writer.WriteString({expr});"]
    if k in ("long", "double"):
        return [f"writer.WriteNumber({expr});"]
    if k == "bool":
        return [f"writer.WriteBoolean({expr});"]
    if k == "mode":
        return [f"writer.WriteString(AgentModes.ToWire({expr}));"]
    if k in ("json", "object"):
        return [f"writer.WriteValue({expr});"]
    if k in ("class", "error"):
        return [f"{expr}.WriteJson(writer);"]
    if k == "list":
        var = f"item{depth}"
        inner = write_value(t.item, var, depth + 1)
        return ["writer.WriteStartArray();", f"foreach (var {var} in {expr})", "{", *["    " + s for s in inner], "}", "writer.WriteEndArray();"]
    raise SchemaError(k)


def write_prop(p: Prop, name: str) -> list[str]:
    t, n = p.type, json.dumps(p.json_name)
    value_expr = name
    if t.kind in ("long", "double", "bool", "mode") and (t.nullable or not p.required):
        value_expr = f"{name}.Value"
    body = [f"writer.WritePropertyName({n});", *write_value(t, value_expr, 0)]
    if p.required and not t.nullable:
        if t.kind in ("json",):
            return [f"writer.WriteValue({n}, {name});"]
        return body
    if p.required and t.nullable:
        null_check = f"{name}.HasValue" if t.kind in ("long", "double", "bool", "mode") else f"{name} is not null"
        return [f"if ({null_check})", "{", *["    " + s for s in body], "}", "else", "{",
                f"    writer.WritePropertyName({n});", "    writer.WriteNull();", "}"]
    # optional
    null_check = f"{name}.HasValue" if t.kind in ("long", "double", "bool", "mode") else f"{name} is not null"
    if t.kind == "json":
        return [f"if ({name} is not null)", "{", f"    writer.WriteValue({n}, {name});", "}"]
    return [f"if ({null_check})", "{", *["    " + s for s in body], "}"]


def default(p: Prop) -> str:
    if not p.required or p.type.nullable:
        return ""
    return {"string": " = string.Empty;", "json": " = JsonNull.Instance;", "object": " = new();", "class": " = new();",
            "list": " = new();", "error": " = new();"}.get(p.type.kind, "")


def emit_class(cls: ClassDef) -> str:
    lines = [f"/// <summary>{xml(cls.description) or cls.name + '.'}</summary>",
             f"public sealed partial class {cls.name} : ProtocolMessage", "{"]
    for p in cls.props:
        doc = xml(p.description) or f"<c>{p.json_name}</c>."
        lines += [f"    /// <summary>{doc}</summary>",
                  f"    public {cs(p.type, not p.required)} {cs_name(cls, p)} {{ get; set; }}{default(p)}", ""]
    lines += [f"    /// <summary>Reads a <see cref=\"{cls.name}\"/> (unknown properties are kept in <see cref=\"ProtocolMessage.Extra\"/>).</summary>",
              f"    public static {cls.name} Read(JsonValue? value, string path)", "    {",
              "        var r = new ObjectReader(value, path);",
              f"        return new {cls.name}", "        {"]
    for p in cls.props:
        lines.append(f"            {cs_name(cls, p)} = {read_expr(p)},")
    lines += ["            Extra = r.Rest(),", "        };", "    }", "",
              "    /// <inheritdoc />", "    protected override void WriteProperties(JsonWriter writer)", "    {"]
    for p in cls.props:
        lines += ["        " + s for s in write_prop(p, cs_name(cls, p))]
    lines += ["    }", "}"]
    return "\n".join(lines)


def render(model: Model) -> dict[str, str]:
    usings = "using System.Collections.Generic;\nusing UnityLudometry.Protocol.Envelopes;\nusing UnityLudometry.Protocol.Json;\n"
    outputs: dict[str, str] = {}

    by_group: dict[str, list[ClassDef]] = {}
    for cls in model.classes.values():
        by_group.setdefault(cls.group, []).append(cls)
    for group, classes in by_group.items():
        body = "\n\n".join(emit_class(c) for c in sorted(classes, key=lambda c: c.name))
        outputs[f"Messages.{pascal(group)}.g.cs"] = f"{HEADER}{usings}\nnamespace {NAMESPACE};\n\n{body}\n"

    thread = {"any": "MethodThread.Any", "main": "MethodThread.Main", "mixed": "MethodThread.Mixed"}
    mode = {"ReadOnly": "AgentMode.ReadOnly", "ReadOnly+Load": "AgentMode.ReadOnlyLoad", "Full": "AgentMode.Full"}
    lines = [HEADER, "namespace UnityLudometry.Protocol;", "",
             "/// <summary>Method names defined by this protocol version.</summary>", "public static class Methods", "{"]
    for m in model.methods:
        lines += [f"    /// <summary>{xml(m.summary)}</summary>", f"    public const string {m.const} = \"{m.name}\";", ""]
    lines[-1:] = ["}", "", "/// <summary>Event kinds defined by this protocol version.</summary>", "public static class EventKinds", "{"]
    for e in model.events:
        lines += [f"    /// <summary>{xml(e.summary)}</summary>", f"    public const string {e.const} = \"{e.kind}\";", ""]
    lines[-1:] = ["}", ""]
    outputs["Names.g.cs"] = "\n".join(lines)
    lines = [HEADER, "using System.Collections.Generic;", "", f"namespace {NAMESPACE};", "",
             "/// <summary>Every method of this protocol version with its execution metadata and message types.</summary>",
             "public static partial class MethodRegistry", "{",
             "    /// <summary>All methods, by name.</summary>",
             "    public static IReadOnlyDictionary<string, MethodDescriptor> All { get; } = "
             "new Dictionary<string, MethodDescriptor>(System.StringComparer.Ordinal)", "    {"]
    for m in model.methods:
        requires = ("new[] { " + ", ".join(json.dumps(r) for r in m.meta.get("requires", [])) + " }"
                    if m.meta.get("requires") else "System.Array.Empty<string>()")
        job = f"{m.job_result.name}.Read" if m.job_result else "null"
        lines.append(f"        [Methods.{m.const}] = new(Methods.{m.const}, {thread[m.meta['thread']]}, {mode[m.meta['minMode']]}, "
                     f"{str(m.meta['job']).lower()}, {str(m.meta['mutating']).lower()}, {requires}, {m.params.name}.Read, {m.result.name}.Read, {job}),")
    lines += ["    };", "}", "", "/// <summary>Every event kind of this protocol version with its payload type.</summary>",
              "public static partial class EventRegistry", "{",
              "    /// <summary>All event kinds.</summary>",
              "    public static IReadOnlyDictionary<string, EventDescriptor> All { get; } = "
              "new Dictionary<string, EventDescriptor>(System.StringComparer.Ordinal)", "    {"]
    for e in model.events:
        lines.append(f"        [EventKinds.{e.const}] = new(EventKinds.{e.const}, {e.params.name}.Read),")
    lines += ["    };", "}", "", "/// <summary>Every exchanged file schema: single-document files and NDJSON record kinds.</summary>",
              "public static partial class FileRegistry", "{",
              "    /// <summary>All file types, keyed by schema name and record kind (empty for single-document files).</summary>",
              "    public static IReadOnlyList<FileRecordDescriptor> All { get; } = new FileRecordDescriptor[]", "    {"]
    for f in model.files:
        lines.append(f"        new(\"{f.schema}\", \"{f.rec}\", {f.type.name}.Read),")
    lines += ["    };", "}", ""]
    outputs["Registry.g.cs"] = "\n".join(lines)
    return outputs


def main() -> int:
    model = build()
    outputs = render(model)
    check = "--check" in sys.argv
    existing = {p.name: p.read_text(encoding="utf-8") for p in OUT_DIR.glob("*.g.cs")} if OUT_DIR.exists() else {}
    if check:
        stale = sorted(set(existing) ^ set(outputs)) + sorted(n for n in outputs if existing.get(n) != outputs[n] and n in existing)
        if stale:
            print("Generated C# is stale: " + ", ".join(stale) + ". Run: python protocol/codegen/csharp.py")
            return 1
        print(f"Generated C# is up to date ({len(model.classes)} types, {len(model.methods)} methods, {len(model.events)} events).")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name in set(existing) - set(outputs):
        (OUT_DIR / name).unlink()
    for name, text in outputs.items():
        (OUT_DIR / name).write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {len(outputs)} files: {len(model.classes)} types, {len(model.methods)} methods, {len(model.events)} events, {len(model.files)} file records.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SchemaError as e:
        print(f"Schema error: {e}")
        sys.exit(2)
