"""Generates the C# message types and registries of UnityLudometry.Protocol from the JSON Schemas.

Usage:  python protocol/codegen/csharp.py           (writes csharp/UnityLudometry.Protocol/Generated/)
        python protocol/codegen/csharp.py --check   (exit 1 if the committed output is stale)

Python 3.10+ standard library only.

Rules:
- A schema object with `properties` becomes a class named by its `title` (required, unique).
- `{"anyOf": [X, {"type": "null"}]}` is a nullable X. Other unions, untyped values and `prefixItems` arrays become JsonValue;
  objects without `properties` become JsonObject.
- Common types with hand-written counterparts: agent-mode → AgentMode, error → ProtocolError, value → JsonValue.
- Required nullable fields are always written; absent optional fields are omitted; unknown properties are kept (Extra).
"""
from __future__ import annotations

import json
import pathlib
import re
import sys
from dataclasses import dataclass, field
from urllib.parse import urljoin, urldefrag

PROTOCOL = pathlib.Path(__file__).resolve().parents[1]
SCHEMA_DIR = PROTOCOL / "schema"
OUT_DIR = PROTOCOL / "csharp" / "UnityLudometry.Protocol" / "Generated"
BASE = "https://github.com/RectangleEquals/UnityLudometryMCP/protocol/schema/"
NAMESPACE = "UnityLudometry.Protocol.Messages"
HEADER = "// <auto-generated>\n// Generated by protocol/codegen/csharp.py from protocol/schema. Do not edit.\n// </auto-generated>\n#nullable enable\n"

SPECIAL = {
    BASE + "common/agent-mode.schema.json#": "mode",
    BASE + "common/error.schema.json#": "error",
    BASE + "common/value.schema.json#": "json",
}


class SchemaError(Exception):
    pass


# ---------------------------------------------------------------- loading and resolving
DOCS: dict[str, dict] = {}
for path in sorted(SCHEMA_DIR.rglob("*.schema.json")):
    rel = path.relative_to(SCHEMA_DIR).as_posix()
    DOCS[BASE + rel] = json.loads(path.read_text(encoding="utf-8"))


def resolve(ref: str, base_uri: str) -> tuple[str, dict]:
    """Returns (absolute uri with fragment, node)."""
    absolute = urljoin(base_uri, ref)
    doc_uri, fragment = urldefrag(absolute)
    if doc_uri not in DOCS:
        raise SchemaError(f"unresolvable $ref {ref} from {base_uri}")
    node = DOCS[doc_uri]
    for part in [p for p in fragment.split("/") if p]:
        part = part.replace("~1", "/").replace("~0", "~")
        node = node[int(part)] if isinstance(node, list) else node[part]
    return f"{doc_uri}#{fragment}", node


# ---------------------------------------------------------------- type model
@dataclass
class CsType:
    kind: str                 # string | long | double | bool | mode | json | object | class | error | list
    name: str = ""            # class name
    item: "CsType | None" = None
    nullable: bool = False     # schema allows JSON null

    def cs(self, optional: bool) -> str:
        base = {"string": "string", "long": "long", "double": "double", "bool": "bool", "mode": "AgentMode",
                "json": "JsonValue", "object": "JsonObject", "error": "ProtocolError"}.get(self.kind)
        if self.kind == "class":
            base = self.name
        if self.kind == "list":
            base = f"List<{self.item.cs(False)}>"
        return base + ("?" if optional or self.nullable else "")


@dataclass
class Prop:
    json_name: str
    cs_name: str
    type: CsType
    required: bool
    description: str


@dataclass
class ClassDef:
    name: str
    description: str
    props: list[Prop] = field(default_factory=list)
    origin: str = ""


CLASSES: dict[str, ClassDef] = {}
NODE_CLASS: dict[str, str] = {}  # node identity (uri#pointer) -> class name
PENDING: list[tuple[str, dict, str]] = []


def pascal(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def map_type(node: dict, uri: str) -> CsType:
    """uri = the node's own identity (document uri + JSON pointer)."""
    if "$ref" in node:
        target_uri, target = resolve(node["$ref"], uri)
        if target_uri in SPECIAL:
            kind = SPECIAL[target_uri]
            return CsType(kind)
        return map_type(target, target_uri)
    if "allOf" in node and len(node["allOf"]) == 1 and "properties" not in node:
        return map_type(node["allOf"][0], uri + "/allOf/0")
    if "allOf" in node and len(node["allOf"]) == 1:
        # A record that extends a single ref (NDJSON records): the referenced type.
        return map_type(node["allOf"][0], uri + "/allOf/0")
    for union in ("anyOf", "oneOf"):
        if union in node and not ("type" in node and node.get("type") == "object" and "properties" in node):
            options = node[union]
            non_null = [o for o in options if o != {"type": "null"}]
            if len(options) == 2 and len(non_null) == 1:
                t = map_type(non_null[0], f"{uri}/{union}/{options.index(non_null[0])}")
                t.nullable = True
                return t
            return CsType("json")
    if "const" in node:
        c = node["const"]
        return CsType("bool" if isinstance(c, bool) else "string" if isinstance(c, str) else "long" if isinstance(c, int) else "double")
    t = node.get("type")
    nullable = False
    if isinstance(t, list):
        types = [x for x in t if x != "null"]
        nullable = "null" in t
        if len(types) != 1:
            return CsType("json")
        t = types[0]
    if t == "string":
        return CsType("string", nullable=nullable)
    if t == "integer":
        return CsType("long", nullable=nullable)
    if t == "number":
        return CsType("double", nullable=nullable)
    if t == "boolean":
        return CsType("bool", nullable=nullable)
    if t == "array":
        if "prefixItems" in node or "items" not in node:
            return CsType("json", nullable=nullable)
        return CsType("list", item=map_type(node["items"], uri + "/items"), nullable=nullable)
    if t == "object" or "properties" in node:
        if "properties" in node:
            return CsType("class", name=register_class(node, uri), nullable=nullable)
        return CsType("object", nullable=nullable)
    return CsType("json")


def register_class(node: dict, uri: str) -> str:
    if uri in NODE_CLASS:
        return NODE_CLASS[uri]
    title = node.get("title")
    if not title or not re.fullmatch(r"[A-Z][A-Za-z0-9]*", title):
        raise SchemaError(f"object with properties needs a PascalCase title: {uri}")
    if title in CLASSES and CLASSES[title].origin != uri:
        raise SchemaError(f"duplicate title {title}: {uri} and {CLASSES[title].origin}")
    NODE_CLASS[uri] = title
    cls = ClassDef(title, node.get("description", ""), origin=uri)
    CLASSES[title] = cls
    required = set(node.get("required", []))
    for json_name, prop_schema in node["properties"].items():
        cs_name = pascal(json_name)
        if cs_name == title or cs_name == "Extra":
            cs_name += "Value"
        ptype = map_type(prop_schema, f"{uri}/properties/{json_name}")
        is_required = json_name in required
        if not is_required and ptype.nullable and ptype.kind not in ("json", "object"):
            raise SchemaError(f"nullable property must be required (canonical form): {uri}/properties/{json_name}")
        cls.props.append(Prop(json_name, cs_name, ptype, is_required, prop_schema.get("description", "")))
    return title


# ---------------------------------------------------------------- code emission
def xml(text: str) -> str:
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = re.sub(r"`([^`]+)`", r"<c>\1</c>", text)
    return " ".join(text.split())


def reader(t: CsType) -> str:
    """A Func<JsonValue, string, T> expression for list items / nested messages."""
    return {
        "string": "ObjectReader.ReadString", "long": "ObjectReader.ReadInt64", "double": "ObjectReader.ReadDouble",
        "bool": "ObjectReader.ReadBoolean", "mode": "ObjectReader.ReadMode", "json": "ObjectReader.ReadValue",
        "object": "ObjectReader.ReadObject", "error": "global::UnityLudometry.Protocol.Envelopes.ProtocolError.Read", "class": f"global::{NAMESPACE}.{t.name}.Read",
    }.get(t.kind) or f"(v, p) => ObjectReader.ReadList(v, p, {reader(t.item)})"


def read_expr(p: Prop) -> str:
    t, n = p.type, json.dumps(p.json_name)
    nullable_required = p.required and t.nullable
    k = t.kind
    if k in ("string", "long", "double", "bool"):
        method = {"string": "String", "long": "Int64", "double": "Double", "bool": "Boolean"}[k]
        if nullable_required:
            return f"r.RequiredNullable{method}({n})"
        return f"r.Required{method}({n})" if p.required else f"r.Optional{method}({n})"
    if k == "mode":
        return f"r.RequiredMode({n})" if p.required else f"r.OptionalMode({n})"
    if k == "json":
        return f"r.RequiredValue({n})" if p.required else f"r.OptionalValue({n})"
    if k == "object":
        return f"r.RequiredObject({n})" if p.required else f"r.OptionalObject({n})"
    if k in ("class", "error"):
        fn = reader(t)
        if nullable_required:
            return f"r.RequiredNullable({n}, {fn})"
        return f"r.Required({n}, {fn})" if p.required else f"r.Optional({n}, {fn})"
    if k == "list":
        return f"r.RequiredArray({n}, {reader(t.item)})" if p.required else f"r.OptionalArray({n}, {reader(t.item)})"
    raise SchemaError(k)


def write_value(t: CsType, expr: str, depth: int) -> list[str]:
    """Statements writing a non-null value (no property name)."""
    k = t.kind
    if k == "string":
        return [f"writer.WriteString({expr});"]
    if k in ("long", "double"):
        return [f"writer.WriteNumber({expr});"]
    if k == "bool":
        return [f"writer.WriteBoolean({expr});"]
    if k == "mode":
        return [f"writer.WriteString(AgentModes.ToWire({expr}));"]
    if k in ("json", "object"):
        return [f"writer.WriteValue({expr});"]
    if k in ("class", "error"):
        return [f"{expr}.WriteJson(writer);"]
    if k == "list":
        var = f"item{depth}"
        inner = write_value(t.item, var, depth + 1)
        return ["writer.WriteStartArray();", f"foreach (var {var} in {expr})", "{", *["    " + s for s in inner], "}", "writer.WriteEndArray();"]
    raise SchemaError(k)


def write_prop(p: Prop) -> list[str]:
    t, n, name = p.type, json.dumps(p.json_name), p.cs_name
    value_expr = name
    if t.kind in ("long", "double", "bool", "mode") and (t.nullable or not p.required):
        value_expr = f"{name}.Value"
    body = [f"writer.WritePropertyName({n});", *write_value(t, value_expr, 0)]
    if p.required and not t.nullable:
        if t.kind in ("json",):
            return [f"writer.WriteValue({n}, {name});"]
        return body
    if p.required and t.nullable:
        null_check = f"{name}.HasValue" if t.kind in ("long", "double", "bool", "mode") else f"{name} is not null"
        return [f"if ({null_check})", "{", *["    " + s for s in body], "}", "else", "{",
                f"    writer.WritePropertyName({n});", "    writer.WriteNull();", "}"]
    # optional
    null_check = f"{name}.HasValue" if t.kind in ("long", "double", "bool", "mode") else f"{name} is not null"
    if t.kind == "json":
        return [f"if ({name} is not null)", "{", f"    writer.WriteValue({n}, {name});", "}"]
    return [f"if ({null_check})", "{", *["    " + s for s in body], "}"]


def default(p: Prop) -> str:
    if not p.required or p.type.nullable:
        return ""
    return {"string": " = string.Empty;", "json": " = JsonNull.Instance;", "object": " = new();", "class": " = new();",
            "list": " = new();", "error": " = new();"}.get(p.type.kind, "")


def emit_class(cls: ClassDef) -> str:
    lines = [f"/// <summary>{xml(cls.description) or cls.name + '.'}</summary>",
             f"public sealed partial class {cls.name} : ProtocolMessage", "{"]
    for p in cls.props:
        doc = xml(p.description) or f"<c>{p.json_name}</c>."
        lines += [f"    /// <summary>{doc}</summary>",
                  f"    public {p.type.cs(not p.required)} {p.cs_name} {{ get; set; }}{default(p)}", ""]
    lines += [f"    /// <summary>Reads a <see cref=\"{cls.name}\"/> (unknown properties are kept in <see cref=\"ProtocolMessage.Extra\"/>).</summary>",
              f"    public static {cls.name} Read(JsonValue? value, string path)", "    {",
              "        var r = new ObjectReader(value, path);",
              f"        return new {cls.name}", "        {"]
    for p in cls.props:
        lines.append(f"            {p.cs_name} = {read_expr(p)},")
    lines += ["            Extra = r.Rest(),", "        };", "    }", "",
              "    /// <inheritdoc />", "    protected override void WriteProperties(JsonWriter writer)", "    {"]
    for p in cls.props:
        lines += ["        " + s for s in write_prop(p)]
    lines += ["    }", "}"]
    return "\n".join(lines)


# ---------------------------------------------------------------- entry points
@dataclass
class MethodEntry:
    name: str
    const: str
    meta: dict
    params: CsType
    result: CsType
    job_result: CsType | None
    summary: str


methods: list = []
events: list = []
files: list = []
outputs: dict[str, str] = {}


def generate() -> None:
    global methods, events, files, outputs
    methods = []
    events = []
    files = []  # (schema name, rec or "", type)

    for uri, doc in DOCS.items():
        rel = uri[len(BASE):]
        if rel.startswith("methods/"):
            name = rel[len("methods/"):-len(".schema.json")]
            if doc.get("title") != name:
                raise SchemaError(f"{rel}: title must be the method name")
            defs = doc["$defs"]
            types = {k: map_type(defs[k], f"{uri}#/$defs/{k}") for k in defs}
            for k in ("params", "result"):
                if types[k].kind != "class":
                    raise SchemaError(f"{rel}: $defs/{k} must be an object type")
            methods.append(MethodEntry(name, pascal(name), doc["x-method"], types["params"], types["result"], types.get("jobResult"), doc["description"]))
        elif rel.startswith("events/"):
            kind = rel[len("events/"):-len(".schema.json")]
            t = map_type(doc["$defs"]["params"], f"{uri}#/$defs/params")
            if t.kind != "class":
                raise SchemaError(f"{rel}: params must be an object type")
            events.append((kind, pascal(kind), t, doc["description"]))
        elif rel.startswith("files/"):
            name = rel[len("files/"):-len(".schema.json")]
            if "properties" in doc:
                files.append((name, "", map_type(doc, uri + "#")))
            for def_name, node in doc.get("$defs", {}).items():
                rec = node.get("x-rec") or node.get("properties", {}).get("rec", {}).get("const")
                if rec and name != "ndjson":
                    files.append((name, rec, map_type(node, f"{uri}#/$defs/{def_name}")))
                elif name == "ndjson":
                    files.append((name, rec, map_type(node, f"{uri}#/$defs/{def_name}")))

    methods.sort(key=lambda m: m.name)
    events.sort(key=lambda e: e[0])
    files.sort(key=lambda f: (f[0], f[1]))
    consts = [m.const for m in methods]
    if len(set(consts)) != len(consts):
        raise SchemaError("method constant names collide")

    # ---------------------------------------------------------------- render files
    USINGS = "using System.Collections.Generic;\nusing UnityLudometry.Protocol.Envelopes;\nusing UnityLudometry.Protocol.Json;\n"
    outputs = {}

    by_group: dict[str, list[ClassDef]] = {}
    for cls in CLASSES.values():
        group = cls.origin[len(BASE):].split("#")[0].split("/")[0]
        by_group.setdefault(group, []).append(cls)
    for group, classes in by_group.items():
        body = "\n\n".join(emit_class(c) for c in sorted(classes, key=lambda c: c.name))
        outputs[f"Messages.{pascal(group)}.g.cs"] = f"{HEADER}{USINGS}\nnamespace {NAMESPACE};\n\n{body}\n"

    THREAD = {"any": "MethodThread.Any", "main": "MethodThread.Main", "mixed": "MethodThread.Mixed"}
    MODE = {"ReadOnly": "AgentMode.ReadOnly", "ReadOnly+Load": "AgentMode.ReadOnlyLoad", "Full": "AgentMode.Full"}
    lines = [HEADER, "namespace UnityLudometry.Protocol;", "",
             "/// <summary>Method names defined by this protocol version.</summary>", "public static class Methods", "{"]
    for m in methods:
        lines += [f"    /// <summary>{xml(m.summary)}</summary>", f"    public const string {m.const} = \"{m.name}\";", ""]
    lines[-1:] = ["}", "", "/// <summary>Event kinds defined by this protocol version.</summary>", "public static class EventKinds", "{"]
    for kind, const, _, summary in events:
        lines += [f"    /// <summary>{xml(summary)}</summary>", f"    public const string {const} = \"{kind}\";", ""]
    lines[-1:] = ["}", ""]
    outputs["Names.g.cs"] = "\n".join(lines)
    lines = [HEADER, "using System.Collections.Generic;", "", f"namespace {NAMESPACE};", "",
             "/// <summary>Every method of this protocol version with its execution metadata and message types.</summary>",
                  "public static partial class MethodRegistry", "{",
                  "    /// <summary>All methods, by name.</summary>",
                  "    public static IReadOnlyDictionary<string, MethodDescriptor> All { get; } = new Dictionary<string, MethodDescriptor>(System.StringComparer.Ordinal)", "    {"]
    for m in methods:
        requires = "new[] { " + ", ".join(json.dumps(r) for r in m.meta.get("requires", [])) + " }" if m.meta.get("requires") else "System.Array.Empty<string>()"
        job = f"{m.job_result.name}.Read" if m.job_result else "null"
        lines.append(f"        [Methods.{m.const}] = new(Methods.{m.const}, {THREAD[m.meta['thread']]}, {MODE[m.meta['minMode']]}, "
                     f"{str(m.meta['job']).lower()}, {str(m.meta['mutating']).lower()}, {requires}, {m.params.name}.Read, {m.result.name}.Read, {job}),")
    lines += ["    };", "}", "", "/// <summary>Every event kind of this protocol version with its payload type.</summary>",
              "public static partial class EventRegistry", "{",
              "    /// <summary>All event kinds.</summary>",
              "    public static IReadOnlyDictionary<string, EventDescriptor> All { get; } = new Dictionary<string, EventDescriptor>(System.StringComparer.Ordinal)", "    {"]
    for kind, const, t, _ in events:
        lines.append(f"        [EventKinds.{const}] = new(EventKinds.{const}, {t.name}.Read),")
    lines += ["    };", "}", "", "/// <summary>Every exchanged file schema: single-document files and NDJSON record kinds.</summary>",
              "public static partial class FileRegistry", "{",
              "    /// <summary>All file types, keyed by schema name and record kind (empty for single-document files).</summary>",
              "    public static IReadOnlyList<FileRecordDescriptor> All { get; } = new FileRecordDescriptor[]", "    {"]
    for name, rec, t in files:
        lines.append(f"        new(\"{name}\", \"{rec}\", {t.name}.Read),")
    lines += ["    };", "}", ""]
    outputs["Registry.g.cs"] = "\n".join(lines)


def main() -> int:
    generate()
    check = "--check" in sys.argv
    existing = {p.name: p.read_text(encoding="utf-8") for p in OUT_DIR.glob("*.g.cs")} if OUT_DIR.exists() else {}
    if check:
        stale = sorted(set(existing) ^ set(outputs)) + sorted(n for n in outputs if existing.get(n) != outputs[n] and n in existing)
        if stale:
            print("Generated C# is stale: " + ", ".join(stale) + ". Run: python protocol/codegen/csharp.py")
            return 1
        print(f"Generated C# is up to date ({len(CLASSES)} types, {len(methods)} methods, {len(events)} events).")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name in set(existing) - set(outputs):
        (OUT_DIR / name).unlink()
    for name, text in outputs.items():
        (OUT_DIR / name).write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {len(outputs)} files: {len(CLASSES)} types, {len(methods)} methods, {len(events)} events, {len(files)} file records.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SchemaError as e:
        print(f"Schema error: {e}")
        sys.exit(2)
