"""Generates the orchestrator's pydantic protocol models and registries from the JSON Schemas.

Usage:  python protocol/codegen/python.py           (writes src/unity_ludometry_mcp/protocol/generated/)
        python protocol/codegen/python.py --check   (exit 1 if the committed output is stale)

Python 3.10+ standard library only (the generated code needs pydantic 2.11+). The schemas are read by schema_ir.py
(shared with the C# generator), so both languages interpret them identically.
Python specifics: fields are snake_case with the JSON name as alias; common types with hand-written counterparts map to
AgentMode, ProtocolError and JsonValue; raw JSON objects map to dict[str, Any]; unknown properties are kept (extra="allow").
"""

from __future__ import annotations

import json
import keyword
import re
import sys

from schema_ir import BASE, DOCS, PROTOCOL, ClassDef, IrType, Model, SchemaError, build

OUT_DIR = PROTOCOL.parent / "src" / "unity_ludometry_mcp" / "protocol" / "generated"
HEADER = "# Generated by protocol/codegen/python.py from protocol/schema. Do not edit.\n# ruff: noqa\n"

# Attribute names of pydantic.BaseModel that a field must not shadow (checked against the installed pydantic by the tests).
RESERVED = {
    "construct",
    "copy",
    "dict",
    "fields",
    "from_orm",
    "json",
    "parse_file",
    "parse_obj",
    "parse_raw",
    "schema",
    "schema_json",
    "update_forward_refs",
    "validate",
    "model_config",
    "model_fields",
    "model_computed_fields",
    "model_extra",
    "model_fields_set",
    "model_construct",
    "model_copy",
    "model_dump",
    "model_dump_json",
    "model_json_schema",
    "model_parametrized_name",
    "model_post_init",
    "model_rebuild",
    "model_validate",
    "model_validate_json",
    "model_validate_strings",
}


def snake(name: str) -> str:
    s = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", name).lower()
    s = re.sub(r"[^a-z0-9_]", "_", s)
    if keyword.iskeyword(s) or s in RESERVED or s.startswith("model_"):
        s += "_"
    return s


def upper_snake(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", name)).upper()


def py(t: IrType) -> str:
    base = {
        "string": "str",
        "long": "Int",
        "double": "float",
        "bool": "bool",
        "mode": "AgentMode",
        "json": "JsonValue",
        "object": "dict[str, Any]",
        "error": "ProtocolError",
    }.get(t.kind)
    if t.kind == "class":
        base = t.name
    if t.kind == "list":
        base = f"list[{py(t.item)}]"
    return base + (" | None" if t.nullable and t.kind != "json" else "")


def text(s: str) -> str:
    return " ".join(s.split())


def emit_class(cls: ClassDef) -> str:
    doc = text(cls.description) or f"{cls.name}."
    lines = [f"class {cls.name}(ProtocolModel):", f"    {json.dumps(doc, ensure_ascii=False)}", ""]
    seen: set[str] = set()
    for p in cls.props:
        name = snake(p.json_name)
        if name in seen:
            raise SchemaError(f"{cls.origin}: two properties map to the Python name {name}")
        seen.add(name)
        annotation = py(p.type)
        args = [f"alias={json.dumps(p.json_name)}"]
        if p.description:
            args.append(f"description={json.dumps(text(p.description), ensure_ascii=False)}")
        if p.required:
            lines.append(f"    {name}: {annotation} = Field({', '.join(args)})")
        else:
            optional = annotation if annotation.endswith("| None") or p.type.kind == "json" else f"{annotation} | None"
            lines.append(f"    {name}: {optional} = Field(default=None, {', '.join(args)})")
    if not cls.props:
        lines.append("    pass")
    return "\n".join(lines)


IMPORTED = {"Any", "Field", "AgentMode", "Int", "JsonValue", "ProtocolError", "ProtocolModel"}


def referenced(t: IrType) -> list[str]:
    if t.kind == "class":
        return [t.name]
    if t.kind == "list":
        return referenced(t.item)
    return []


def dependency_order(model: Model) -> list[ClassDef]:
    """Classes ordered so that every referenced class is defined first (cycles fall back to forward references).
    This matters for names that also exist as builtins (e.g. Warning): a forward reference would bind the builtin."""
    ordered: list[ClassDef] = []
    state: dict[str, str] = {}

    def visit(name: str) -> None:
        if state.get(name):
            return
        state[name] = "visiting"
        cls = model.classes[name]
        for p in cls.props:
            for dep in referenced(p.type):
                visit(dep)
        state[name] = "done"
        ordered.append(cls)

    for name in sorted(model.classes):
        visit(name)
    return ordered


def render(model: Model) -> dict[str, str]:
    clashes = sorted(set(model.classes) & IMPORTED)
    if clashes:
        raise SchemaError(f"class names clash with the generated module's imports: {', '.join(clashes)}")
    classes = dependency_order(model)
    body = "\n\n\n".join(emit_class(c) for c in classes)
    rebuild = "\n".join(f"{c.name}.model_rebuild()" for c in classes)
    names = ", ".join(json.dumps(name) for name in sorted(model.classes))
    models = (
        f"{HEADER}from __future__ import annotations\n\nfrom typing import Any\n\nfrom pydantic import Field\n\n"
        "from ..base import AgentMode, Int, JsonValue, ProtocolError, ProtocolModel\n\n"
        f"__all__ = [{names}]\n\n\n{body}\n\n\n{rebuild}\n"
    )

    thread = {"any": "MethodThread.ANY", "main": "MethodThread.MAIN", "mixed": "MethodThread.MIXED"}
    error_codes = DOCS[BASE + "common/error.schema.json"]["properties"]["code"]["examples"]
    lines = [
        HEADER,
        "from ..base import EventDescriptor, FileRecordDescriptor, MethodDescriptor, MethodThread",
        "from . import models as m",
        "",
        "",
        "class Methods:",
        '    """Method names defined by this protocol version."""',
        "",
    ]
    for meth in model.methods:
        lines.append(f"    {upper_snake(meth.const)} = {json.dumps(meth.name)}")
    lines += ["", "", "class EventKinds:", '    """Event kinds defined by this protocol version."""', ""]
    for e in model.events:
        lines.append(f"    {upper_snake(e.const)} = {json.dumps(e.kind)}")
    lines += ["", "", "class ErrorCodes:", '    """Error codes defined by the protocol. Treat unknown codes as generic failures."""', ""]
    for code in error_codes:
        lines.append(f"    {code} = {json.dumps(code)}")
    lines += ["", "", "METHODS: dict[str, MethodDescriptor] = {"]
    for meth in model.methods:
        requires = "(" + "".join(f"{json.dumps(r)}, " for r in meth.meta.get("requires", [])) + ")"
        job = f"m.{meth.job_result.name}" if meth.job_result else "None"
        lines.append(
            f"    Methods.{upper_snake(meth.const)}: MethodDescriptor({json.dumps(meth.name)}, {thread[meth.meta['thread']]}, "
            f"{json.dumps(meth.meta['minMode'])}, {meth.meta['job']}, {meth.meta['mutating']}, {requires}, "
            f"m.{meth.params.name}, m.{meth.result.name}, {job}),"
        )
    lines += ["}", '"""All methods, by name."""', "", "EVENTS: dict[str, EventDescriptor] = {"]
    for e in model.events:
        lines.append(f"    EventKinds.{upper_snake(e.const)}: EventDescriptor({json.dumps(e.kind)}, m.{e.params.name}),")
    lines += ["}", '"""All event kinds."""', "", "FILES: tuple[FileRecordDescriptor, ...] = ("]
    for f in model.files:
        lines.append(f"    FileRecordDescriptor({json.dumps(f.schema)}, {json.dumps(f.rec)}, m.{f.type.name}),")
    lines += [")", '"""All file types: single-document files (empty rec) and NDJSON record kinds."""']
    registry = "\n".join(lines) + "\n"
    init = f"{HEADER}from .models import *  # noqa: F403\nfrom .registry import EVENTS, FILES, METHODS, ErrorCodes, EventKinds, Methods\n"
    return {"models.py": models, "registry.py": registry, "__init__.py": init}


def main() -> int:
    model = build()
    outputs = render(model)
    check = "--check" in sys.argv
    existing = {p.name: p.read_text(encoding="utf-8") for p in OUT_DIR.glob("*.py")} if OUT_DIR.exists() else {}
    if check:
        stale = sorted(set(existing) ^ set(outputs)) + sorted(n for n in outputs if n in existing and existing[n] != outputs[n])
        if stale:
            print("Generated Python is stale: " + ", ".join(stale) + ". Run: python protocol/codegen/python.py")
            return 1
        print(f"Generated Python is up to date ({len(model.classes)} types, {len(model.methods)} methods, {len(model.events)} events).")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name in set(existing) - set(outputs):
        (OUT_DIR / name).unlink()
    for name, content in outputs.items():
        (OUT_DIR / name).write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {len(outputs)} files: {len(model.classes)} types, {len(model.methods)} methods, {len(model.events)} events, {len(model.files)} file records.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SchemaError as e:
        print(f"Schema error: {e}")
        sys.exit(2)
