<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Build-time only (no runtime dependency)">
    <PackageVersion Include="PolySharp" Version="1.16.0" />
  </ItemGroup>
</Project>
