"""Generates the tool reference (docs/tools.md) from the server's tool definitions.

uv run python tools/tool_reference.py [--check]
"""

import asyncio
import sys
from pathlib import Path
from typing import Any

from unity_ludometry_mcp.server import create_server

REPO = Path(__file__).resolve().parents[1]
OUTPUT = REPO / "docs" / "tools.md"

_HINTS = [("readOnlyHint", "read-only"), ("destructiveHint", "changes things"), ("idempotentHint", "repeatable")]


def _params(schema: dict[str, Any]) -> list[str]:
    properties: dict[str, Any] = schema.get("properties", {})
    required = set(schema.get("required", []))
    if not properties:
        return ["_No parameters._"]
    lines = ["| Parameter | Type | Required | Description |", "|---|---|---|---|"]
    for name, spec in properties.items():
        kind = spec.get("type", "any")
        kind = " \\| ".join(kind) if isinstance(kind, list) else kind
        description = " ".join(str(spec.get("description", "")).split())
        lines.append(f"| `{name}` | {kind} | {'yes' if name in required else 'no'} | {description} |")
    return lines


async def render() -> str:
    tools = [t.to_mcp_tool().model_dump(mode="json", by_alias=True, exclude_none=True) for t in await create_server().list_tools()]
    out = [
        "# Tool reference",
        "",
        "<!-- Generated by tools/tool_reference.py from the server's tool definitions. Do not edit. -->",
        "",
        "The tools UnityLudometryMCP offers to your AI assistant. More tools arrive as the orchestrator grows.",
        "",
    ]
    for tool in tools:
        annotations = tool.get("annotations", {})
        traits = [label for key, label in _HINTS if annotations.get(key)]
        out += [f"## `{tool['name']}`", ""]
        if tool.get("title"):
            out += [f"**{tool['title']}**" + (f" · {', '.join(traits)}" if traits else ""), ""]
        out += [" ".join(tool.get("description", "").split()), ""]
        out += _params(tool.get("inputSchema", {}))
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    text = asyncio.run(render())
    if argv == ["--check"]:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.relative_to(REPO).as_posix()} is out of date: run `uv run python tools/tool_reference.py`.")
            return 1
        count = text.count("\n## `")
        print(f"Tool reference is up to date ({count} tool{'' if count == 1 else 's'}).")
        return 0
    if argv:
        print(__doc__)
        return 2
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(REPO).as_posix()}.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
